VIH-7946 video web url fix
hmcts/vh-service-web pull request #689
Opened 2021-09-22 15:43 UTC by lowflying

### JIRA link (if applicable) ###
N/A

### Change description ###

added logic for the VhServices:VideoWebUrl app setting so it plays nice with the vanity urls in prod/preprod

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2021-09-22 15:55 UTC, robertbennett1998 requested changes

2021-09-22 15:55 UTC, robertbennett1998 commented on azure-pipelines.release.yml
> +            ${{ if containsValue('preview', parameters.environment) }}:
Should this be preprod?

2021-09-22 15:55 UTC, robertbennett1998 commented on azure-pipelines.release.yml
> +            ${{ if not(or(containsValue('preprod', parameters.environment), containsValue('preprod', parameters.environment))) }}:
Should this be if 
`not(or(containsValue('preprod', parameters.environment), containsValue('prod', parameters.environment))) ?`

2021-09-22 15:59 UTC, lowflying commented
/azp run

2021-09-22 16:02 UTC, lowflying commented on azure-pipelines.release.yml
> +            ${{ if containsValue('preview', parameters.environment) }}:
yes indeed it should

2021-09-22 16:02 UTC, lowflying commented
/azp run

2021-09-22 16:06 UTC, vialde approved these changes

2021-09-24 08:03 UTC, robertbennett1998 approved these changes
LGTM

2021-09-24 08:45 UTC, vialde approved these changes

2021-09-24 08:49 UTC, merged